import type { InvitationView } from '@/lib/invitations';

const previewData: InvitationView = {
  invitation: {
    id: 'preview-invitation',
    slug: 'ulems-preview',
    title: 'The Wedding of Ulem & Sari',
    groom_name: 'Ulem Pratama',
    bride_name: 'Sari Lestari',
    groom_nickname: 'Ulem',
    bride_nickname: 'Sari',
    groom_parents: 'Putra dari Bapak Ahmad & Ibu Aminah',
    bride_parents: 'Putri dari Bapak Budiman & Ibu Cici',
    date_display: 'Sabtu, 20 Juli 2024',
    theme_slug: 'ulems',
    cover_photo_url: 'https://images.unsplash.com/photo-1520854221050-0f4caff449fb?auto=format&fit=crop&w=1200&q=80',
    music_url: '',
    user_id: 'preview-user',
    custom_domain_suffix: null,
    view_count: null,
    is_published: true,
    pages_enabled: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  events: [
    {
      id: 'event-akad',
      invitation_id: 'preview-invitation',
      type: 'akad',
      title: 'Akad Nikah',
      date: '2024-07-20',
      time: '08.00 WIB',
      date_display: 'Sabtu, 20 Juli 2024',
      location: 'Masjid Raya Baiturrahman, Banda Aceh',
      map_url: 'https://maps.app.goo.gl/some-akad',
      latitude: 5.553956,
      longitude: 95.317467,
      note: 'Mohon hadir 15 menit sebelum acara dimulai.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'event-resepsi',
      invitation_id: 'preview-invitation',
      type: 'resepsi',
      title: 'Resepsi',
      date: '2024-07-20',
      time: '11.00 - 14.00 WIB',
      date_display: 'Sabtu, 20 Juli 2024',
      location: 'Gedung Serbaguna Ule Kareng, Banda Aceh',
      map_url: 'https://maps.app.goo.gl/some-resepsi',
      latitude: 5.518757,
      longitude: 95.370003,
      note: 'Dress code: Batik modern atau busana sopan.',
      created_at: new Date().toISOString(),
    },
  ],
  media: [
    {
      id: 'media-cover',
      invitation_id: 'preview-invitation',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1520854221050-0f4caff449fb?auto=format&fit=crop&w=1000&q=80',
      caption: 'Momen penuh cinta',
      sort_index: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 'media-gallery-1',
      invitation_id: 'preview-invitation',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=80',
      caption: 'Pertunangan Bahagia',
      sort_index: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: 'media-gallery-2',
      invitation_id: 'preview-invitation',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1520854221050-0f4caff449fb?auto=format&fit=crop&w=1000&q=80',
      caption: 'Senja Bersama',
      sort_index: 2,
      created_at: new Date().toISOString(),
    },
  ],
  stories: [
    {
      id: 'story-1',
      invitation_id: 'preview-invitation',
      title: 'Pertemuan Pertama',
      body: 'Kami bertemu pada sebuah acara kampus dan langsung merasa cocok.',
      date: '2017-02-12',
      date_display: 'Februari 2017',
      photo_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80',
      sort_index: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 'story-2',
      invitation_id: 'preview-invitation',
      title: 'Lamaran',
      body: 'Keluarga besar berkumpul menyaksikan momen lamaran penuh haru.',
      date: '2023-11-15',
      date_display: 'November 2023',
      photo_url: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=800&q=80',
      sort_index: 1,
      created_at: new Date().toISOString(),
    },
  ],
  gift: {
    id: 'gift-1',
    invitation_id: 'preview-invitation',
    bank_name: 'BCA',
    account_number: '1234567890',
    account_name: 'Ulem Pratama',
    qr_image_url: 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92eee?auto=format&fit=crop&w=600&q=80',
  },
  guests: [
    {
      id: 'guest-1',
      invitation_id: 'preview-invitation',
      name: 'Rahma',
      status: 'pending',
      message: 'Selamat menempuh hidup baru, semoga selalu bahagia!',
      seats: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'guest-2',
      invitation_id: 'preview-invitation',
      name: 'Budi & Keluarga',
      status: 'yes',
      message: 'InsyaAllah hadir. Sampai bertemu di hari bahagia kalian!',
      seats: null,
      created_at: new Date().toISOString(),
    },
  ],
};

export default previewData;
